experiment_name: "251126"
wandb_project_name: "MUSE-VAE"

# -------------------------------------------------------------------
# Dataset / Data Processing
# -------------------------------------------------------------------
root_dir: "./"
data_dir: "model_outputs"
batch_size: 64
data_mean: 0.5
data_std: 0.5

train_dataset: "train.csv"
val_dataset: "val.csv"
test_dataset: "test.csv"

# -------------------------------------------------------------------
# Training & Optimization
# -------------------------------------------------------------------
epochs: 200
lr: 0.0001
patience: 25
check_val_every_n_epoch: 1
test_every_n_epochs: 50

# Optionally, a warm-up phase
warmup: true
warmup_steps: 1000

# -------------------------------------------------------------------
# Model Architecture
# -------------------------------------------------------------------
model_name: "MUSE-VAE"
latent_dim: 16
#-------------------------------------------------------------------
# Prediction & Evaluation
# -------------------------------------------------------------------
checkpoint_path: /home/trfar/Documents/Advanced Machine 
  Learning/TrainedModels/251126/checkpoints/epochepoch=171-val_lossval_loss=0.0684.ckpt
output_dir: "./model_outputs"

Gaussian Fitting: false
Statistical Analysis PDF: true
